<?php
/**
 * Shipment20240911
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Webcom\Amazon\Rest\ExternalFulfillment20240911
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for Amazon External Fulfillment Shipments Processing
 *
 * You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.
 *
 * The version of the OpenAPI document: 2024-09-11
 * Contact: marketplaceapitest@amazon.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Webcom\Amazon\Rest\ExternalFulfillment20240911\Model;

use \Webcom\Amazon\Rest\ModelInterface;
use \ArrayAccess;
use \Webcom\Amazon\Rest\ObjectSerializer;

/**
 * Shipment20240911 Class Doc Comment
 *
 * @category Class
 * @description Information about a shipment.
 * @package  Webcom\Amazon\Rest\ExternalFulfillment20240911
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class Shipment20240911 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Shipment';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'locationId' => 'string',
        'marketplaceAttributes' => '\Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\MarketplaceAttributes20240911',
        'shipmentInfo' => '\Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\ShipmentInfo20240911',
        'invoiceInfo' => '\Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\InvoiceInfo20240911',
        'partyInfoList' => '\Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\PartyIdentificationInfo20240911[]',
        'shipmentRequirements' => '\Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\ShipmentRequirements20240911',
        'charges' => '\Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\Charge20240911[]',
        'status' => 'string',
        'subStatus' => 'string',
        'reason' => 'string',
        'lineItems' => '\Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\ShipmentLineItem20240911[]',
        'shippingInfo' => '\Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\ShippingInfo20240911',
        'packages' => '\Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\Package20240911[]',
        'creationDateTime' => 'string',
        'lastUpdatedDateTime' => 'string',
        'earliestPackDateTime' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'locationId' => null,
        'marketplaceAttributes' => null,
        'shipmentInfo' => null,
        'invoiceInfo' => null,
        'partyInfoList' => null,
        'shipmentRequirements' => null,
        'charges' => null,
        'status' => null,
        'subStatus' => null,
        'reason' => null,
        'lineItems' => null,
        'shippingInfo' => null,
        'packages' => null,
        'creationDateTime' => null,
        'lastUpdatedDateTime' => null,
        'earliestPackDateTime' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'locationId' => 'locationId',
        'marketplaceAttributes' => 'marketplaceAttributes',
        'shipmentInfo' => 'shipmentInfo',
        'invoiceInfo' => 'invoiceInfo',
        'partyInfoList' => 'partyInfoList',
        'shipmentRequirements' => 'shipmentRequirements',
        'charges' => 'charges',
        'status' => 'status',
        'subStatus' => 'subStatus',
        'reason' => 'reason',
        'lineItems' => 'lineItems',
        'shippingInfo' => 'shippingInfo',
        'packages' => 'packages',
        'creationDateTime' => 'creationDateTime',
        'lastUpdatedDateTime' => 'lastUpdatedDateTime',
        'earliestPackDateTime' => 'earliestPackDateTime'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'locationId' => 'setLocationId',
        'marketplaceAttributes' => 'setMarketplaceAttributes',
        'shipmentInfo' => 'setShipmentInfo',
        'invoiceInfo' => 'setInvoiceInfo',
        'partyInfoList' => 'setPartyInfoList',
        'shipmentRequirements' => 'setShipmentRequirements',
        'charges' => 'setCharges',
        'status' => 'setStatus',
        'subStatus' => 'setSubStatus',
        'reason' => 'setReason',
        'lineItems' => 'setLineItems',
        'shippingInfo' => 'setShippingInfo',
        'packages' => 'setPackages',
        'creationDateTime' => 'setCreationDateTime',
        'lastUpdatedDateTime' => 'setLastUpdatedDateTime',
        'earliestPackDateTime' => 'setEarliestPackDateTime'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'locationId' => 'getLocationId',
        'marketplaceAttributes' => 'getMarketplaceAttributes',
        'shipmentInfo' => 'getShipmentInfo',
        'invoiceInfo' => 'getInvoiceInfo',
        'partyInfoList' => 'getPartyInfoList',
        'shipmentRequirements' => 'getShipmentRequirements',
        'charges' => 'getCharges',
        'status' => 'getStatus',
        'subStatus' => 'getSubStatus',
        'reason' => 'getReason',
        'lineItems' => 'getLineItems',
        'shippingInfo' => 'getShippingInfo',
        'packages' => 'getPackages',
        'creationDateTime' => 'getCreationDateTime',
        'lastUpdatedDateTime' => 'getLastUpdatedDateTime',
        'earliestPackDateTime' => 'getEarliestPackDateTime'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const STATUS_CREATED = 'CREATED';
    const STATUS_ACCEPTED = 'ACCEPTED';
    const STATUS_CONFIRMED = 'CONFIRMED';
    const STATUS_PACKAGE_CREATED = 'PACKAGE_CREATED';
    const STATUS_PICKUP_SLOT_RETRIEVED = 'PICKUP_SLOT_RETRIEVED';
    const STATUS_INVOICE_GENERATED = 'INVOICE_GENERATED';
    const STATUS_SHIPLABEL_GENERATED = 'SHIPLABEL_GENERATED';
    const STATUS_CANCELLED = 'CANCELLED';
    const STATUS_SHIPPED = 'SHIPPED';
    const STATUS_DELIVERED = 'DELIVERED';
    const SUB_STATUS_PENDING_SCHEDULE = 'PENDING_SCHEDULE';
    const SUB_STATUS_PENDING_PICKUP = 'PENDING_PICKUP';
    const SUB_STATUS_PENDING_DROP_OFF = 'PENDING_DROP_OFF';
    const SUB_STATUS_LABEL_CANCELED = 'LABEL_CANCELED';
    const SUB_STATUS_PICKED_UP = 'PICKED_UP';
    const SUB_STATUS_DROPPED_OFF = 'DROPPED_OFF';
    const SUB_STATUS_AT_ORIGIN_FC = 'AT_ORIGIN_FC';
    const SUB_STATUS_AT_DESTINATION_FC = 'AT_DESTINATION_FC';
    const SUB_STATUS_DELIVERED = 'DELIVERED';
    const SUB_STATUS_NOT_DELIVERED = 'NOT_DELIVERED';
    const SUB_STATUS_UNDELIVERABLE = 'UNDELIVERABLE';
    const SUB_STATUS_LOST = 'LOST';
    const SUB_STATUS_OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY';
    const SUB_STATUS_DAMAGED = 'DAMAGED';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_CREATED,
            self::STATUS_ACCEPTED,
            self::STATUS_CONFIRMED,
            self::STATUS_PACKAGE_CREATED,
            self::STATUS_PICKUP_SLOT_RETRIEVED,
            self::STATUS_INVOICE_GENERATED,
            self::STATUS_SHIPLABEL_GENERATED,
            self::STATUS_CANCELLED,
            self::STATUS_SHIPPED,
            self::STATUS_DELIVERED,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSubStatusAllowableValues()
    {
        return [
            self::SUB_STATUS_PENDING_SCHEDULE,
            self::SUB_STATUS_PENDING_PICKUP,
            self::SUB_STATUS_PENDING_DROP_OFF,
            self::SUB_STATUS_LABEL_CANCELED,
            self::SUB_STATUS_PICKED_UP,
            self::SUB_STATUS_DROPPED_OFF,
            self::SUB_STATUS_AT_ORIGIN_FC,
            self::SUB_STATUS_AT_DESTINATION_FC,
            self::SUB_STATUS_DELIVERED,
            self::SUB_STATUS_NOT_DELIVERED,
            self::SUB_STATUS_UNDELIVERABLE,
            self::SUB_STATUS_LOST,
            self::SUB_STATUS_OUT_FOR_DELIVERY,
            self::SUB_STATUS_DAMAGED,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['locationId'] = $data['locationId'] ?? null;
        $this->container['marketplaceAttributes'] = $data['marketplaceAttributes'] ?? null;
        $this->container['shipmentInfo'] = $data['shipmentInfo'] ?? null;
        $this->container['invoiceInfo'] = $data['invoiceInfo'] ?? null;
        $this->container['partyInfoList'] = $data['partyInfoList'] ?? null;
        $this->container['shipmentRequirements'] = $data['shipmentRequirements'] ?? null;
        $this->container['charges'] = $data['charges'] ?? null;
        $this->container['status'] = $data['status'] ?? null;
        $this->container['subStatus'] = $data['subStatus'] ?? null;
        $this->container['reason'] = $data['reason'] ?? null;
        $this->container['lineItems'] = $data['lineItems'] ?? null;
        $this->container['shippingInfo'] = $data['shippingInfo'] ?? null;
        $this->container['packages'] = $data['packages'] ?? null;
        $this->container['creationDateTime'] = $data['creationDateTime'] ?? null;
        $this->container['lastUpdatedDateTime'] = $data['lastUpdatedDateTime'] ?? null;
        $this->container['earliestPackDateTime'] = $data['earliestPackDateTime'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['locationId'] === null) {
            $invalidProperties[] = "'locationId' can't be null";
        }
        if ($this->container['marketplaceAttributes'] === null) {
            $invalidProperties[] = "'marketplaceAttributes' can't be null";
        }
        if ($this->container['shipmentInfo'] === null) {
            $invalidProperties[] = "'shipmentInfo' can't be null";
        }
        if ($this->container['shipmentRequirements'] === null) {
            $invalidProperties[] = "'shipmentRequirements' can't be null";
        }
        if ($this->container['charges'] === null) {
            $invalidProperties[] = "'charges' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSubStatusAllowableValues();
        if (!is_null($this->container['subStatus']) && !in_array($this->container['subStatus'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'subStatus', must be one of '%s'",
                $this->container['subStatus'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['lineItems'] === null) {
            $invalidProperties[] = "'lineItems' can't be null";
        }
        if ($this->container['shippingInfo'] === null) {
            $invalidProperties[] = "'shippingInfo' can't be null";
        }
        if ($this->container['creationDateTime'] === null) {
            $invalidProperties[] = "'creationDateTime' can't be null";
        }
        if ($this->container['lastUpdatedDateTime'] === null) {
            $invalidProperties[] = "'lastUpdatedDateTime' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id The shipment's ID.
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets locationId
     *
     * @return string
     */
    public function getLocationId()
    {
        return $this->container['locationId'];
    }

    /**
     * Sets locationId
     *
     * @param string $locationId The location identifier of the seller's location in the marketplace channel to which the shipment has been created for fulfillment.
     *
     * @return self
     */
    public function setLocationId($locationId)
    {
        $this->container['locationId'] = $locationId;

        return $this;
    }

    /**
     * Gets marketplaceAttributes
     *
     * @return \Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\MarketplaceAttributes20240911
     */
    public function getMarketplaceAttributes()
    {
        return $this->container['marketplaceAttributes'];
    }

    /**
     * Sets marketplaceAttributes
     *
     * @param \Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\MarketplaceAttributes20240911 $marketplaceAttributes marketplaceAttributes
     *
     * @return self
     */
    public function setMarketplaceAttributes($marketplaceAttributes)
    {
        $this->container['marketplaceAttributes'] = $marketplaceAttributes;

        return $this;
    }

    /**
     * Gets shipmentInfo
     *
     * @return \Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\ShipmentInfo20240911
     */
    public function getShipmentInfo()
    {
        return $this->container['shipmentInfo'];
    }

    /**
     * Sets shipmentInfo
     *
     * @param \Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\ShipmentInfo20240911 $shipmentInfo shipmentInfo
     *
     * @return self
     */
    public function setShipmentInfo($shipmentInfo)
    {
        $this->container['shipmentInfo'] = $shipmentInfo;

        return $this;
    }

    /**
     * Gets invoiceInfo
     *
     * @return \Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\InvoiceInfo20240911|null
     */
    public function getInvoiceInfo()
    {
        return $this->container['invoiceInfo'];
    }

    /**
     * Sets invoiceInfo
     *
     * @param \Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\InvoiceInfo20240911|null $invoiceInfo invoiceInfo
     *
     * @return self
     */
    public function setInvoiceInfo($invoiceInfo)
    {
        $this->container['invoiceInfo'] = $invoiceInfo;

        return $this;
    }

    /**
     * Gets partyInfoList
     *
     * @return \Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\PartyIdentificationInfo20240911[]|null
     */
    public function getPartyInfoList()
    {
        return $this->container['partyInfoList'];
    }

    /**
     * Sets partyInfoList
     *
     * @param \Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\PartyIdentificationInfo20240911[]|null $partyInfoList All involved party identification and metadata for the vendor, buyer, and seller. Applicable for direct-fulfillment sellers.
     *
     * @return self
     */
    public function setPartyInfoList($partyInfoList)
    {
        $this->container['partyInfoList'] = $partyInfoList;

        return $this;
    }

    /**
     * Gets shipmentRequirements
     *
     * @return \Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\ShipmentRequirements20240911
     */
    public function getShipmentRequirements()
    {
        return $this->container['shipmentRequirements'];
    }

    /**
     * Sets shipmentRequirements
     *
     * @param \Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\ShipmentRequirements20240911 $shipmentRequirements shipmentRequirements
     *
     * @return self
     */
    public function setShipmentRequirements($shipmentRequirements)
    {
        $this->container['shipmentRequirements'] = $shipmentRequirements;

        return $this;
    }

    /**
     * Gets charges
     *
     * @return \Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\Charge20240911[]
     */
    public function getCharges()
    {
        return $this->container['charges'];
    }

    /**
     * Sets charges
     *
     * @param \Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\Charge20240911[] $charges The charges associated with the shipment.
     *
     * @return self
     */
    public function setCharges($charges)
    {
        $this->container['charges'] = $charges;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status The current status of the shipment.
     *
     * @return self
     */
    public function setStatus($status)
    {
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets subStatus
     *
     * @return string|null
     */
    public function getSubStatus()
    {
        return $this->container['subStatus'];
    }

    /**
     * Sets subStatus
     *
     * @param string|null $subStatus The sub status of the shipment.
     *
     * @return self
     */
    public function setSubStatus($subStatus)
    {
        $allowedValues = $this->getSubStatusAllowableValues();
        if (!is_null($subStatus) && !in_array($subStatus, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'subStatus', must be one of '%s'",
                    $subStatus,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['subStatus'] = $subStatus;

        return $this;
    }

    /**
     * Gets reason
     *
     * @return string|null
     */
    public function getReason()
    {
        return $this->container['reason'];
    }

    /**
     * Sets reason
     *
     * @param string|null $reason The reason for the sub-status.
     *
     * @return self
     */
    public function setReason($reason)
    {
        $this->container['reason'] = $reason;

        return $this;
    }

    /**
     * Gets lineItems
     *
     * @return \Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\ShipmentLineItem20240911[]
     */
    public function getLineItems()
    {
        return $this->container['lineItems'];
    }

    /**
     * Sets lineItems
     *
     * @param \Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\ShipmentLineItem20240911[] $lineItems The line items in the shipment.
     *
     * @return self
     */
    public function setLineItems($lineItems)
    {
        $this->container['lineItems'] = $lineItems;

        return $this;
    }

    /**
     * Gets shippingInfo
     *
     * @return \Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\ShippingInfo20240911
     */
    public function getShippingInfo()
    {
        return $this->container['shippingInfo'];
    }

    /**
     * Sets shippingInfo
     *
     * @param \Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\ShippingInfo20240911 $shippingInfo shippingInfo
     *
     * @return self
     */
    public function setShippingInfo($shippingInfo)
    {
        $this->container['shippingInfo'] = $shippingInfo;

        return $this;
    }

    /**
     * Gets packages
     *
     * @return \Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\Package20240911[]|null
     */
    public function getPackages()
    {
        return $this->container['packages'];
    }

    /**
     * Sets packages
     *
     * @param \Webcom\Amazon\Rest\ExternalFulfillment20240911\Model\Package20240911[]|null $packages The list of packages in the shipment.
     *
     * @return self
     */
    public function setPackages($packages)
    {
        $this->container['packages'] = $packages;

        return $this;
    }

    /**
     * Gets creationDateTime
     *
     * @return string
     */
    public function getCreationDateTime()
    {
        return $this->container['creationDateTime'];
    }

    /**
     * Sets creationDateTime
     *
     * @param string $creationDateTime A date and time in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     *
     * @return self
     */
    public function setCreationDateTime($creationDateTime)
    {
        $this->container['creationDateTime'] = $creationDateTime;

        return $this;
    }

    /**
     * Gets lastUpdatedDateTime
     *
     * @return string
     */
    public function getLastUpdatedDateTime()
    {
        return $this->container['lastUpdatedDateTime'];
    }

    /**
     * Sets lastUpdatedDateTime
     *
     * @param string $lastUpdatedDateTime A date and time in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     *
     * @return self
     */
    public function setLastUpdatedDateTime($lastUpdatedDateTime)
    {
        $this->container['lastUpdatedDateTime'] = $lastUpdatedDateTime;

        return $this;
    }

    /**
     * Gets earliestPackDateTime
     *
     * @return string|null
     */
    public function getEarliestPackDateTime()
    {
        return $this->container['earliestPackDateTime'];
    }

    /**
     * Sets earliestPackDateTime
     *
     * @param string|null $earliestPackDateTime A date and time in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     *
     * @return self
     */
    public function setEarliestPackDateTime($earliestPackDateTime)
    {
        $this->container['earliestPackDateTime'] = $earliestPackDateTime;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


