<?php
/**
 * EventCodeV2
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Webcom\Amazon\Rest\ShippingApiV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Webcom\Amazon\Rest\ShippingApiV2\Model;
use \Webcom\Amazon\Rest\ObjectSerializer;

/**
 * EventCodeV2 Class Doc Comment
 *
 * @category Class
 * @description The tracking event type.
 * @package  Webcom\Amazon\Rest\ShippingApiV2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EventCodeV2
{
    /**
     * Possible values of this enum
     */
    const READY_FOR_RECEIVE = 'ReadyForReceive';
    const PICKUP_DONE = 'PickupDone';
    const DELIVERED = 'Delivered';
    const DEPARTED = 'Departed';
    const DELIVERY_ATTEMPTED = 'DeliveryAttempted';
    const LOST = 'Lost';
    const OUT_FOR_DELIVERY = 'OutForDelivery';
    const ARRIVED_AT_CARRIER_FACILITY = 'ArrivedAtCarrierFacility';
    const REJECTED = 'Rejected';
    const UNDELIVERABLE = 'Undeliverable';
    const PICKUP_CANCELLED = 'PickupCancelled';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::READY_FOR_RECEIVE,
            self::PICKUP_DONE,
            self::DELIVERED,
            self::DEPARTED,
            self::DELIVERY_ATTEMPTED,
            self::LOST,
            self::OUT_FOR_DELIVERY,
            self::ARRIVED_AT_CARRIER_FACILITY,
            self::REJECTED,
            self::UNDELIVERABLE,
            self::PICKUP_CANCELLED,
        ];
    }
}


