<?php
/**
 * OrderChangeTypeEnum
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Webcom\Amazon\Rest\NotificationsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Selling Partner API for Notifications
 *
 * The Selling Partner API for Notifications lets you subscribe to notifications that are relevant to a selling partner's business. Using this API you can create a destination to receive notifications, subscribe to notifications, delete notification subscriptions, and more.  For more information, refer to the [Notifications Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide).
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Webcom\Amazon\Rest\NotificationsApi\Model;
use \Webcom\Amazon\Rest\ObjectSerializer;

/**
 * OrderChangeTypeEnum Class Doc Comment
 *
 * @category Class
 * @description The supported order change type of ORDER_CHANGE notification.
 * @package  Webcom\Amazon\Rest\NotificationsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderChangeTypeEnum
{
    /**
     * Possible values of this enum
     */
    const ORDER_STATUS_CHANGE = 'OrderStatusChange';
    const BUYER_REQUESTED_CHANGE = 'BuyerRequestedChange';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ORDER_STATUS_CHANGE,
            self::BUYER_REQUESTED_CHANGE,
        ];
    }
}


