<?php
/**
 * InboundPlanSummary20240320
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Webcom\Amazon\Rest\FulfillmentInboundApi20240320
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * The version of the OpenAPI document: 2024-03-20
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Webcom\Amazon\Rest\FulfillmentInboundApi20240320\Model;

use \Webcom\Amazon\Rest\ModelInterface;
use \ArrayAccess;
use \Webcom\Amazon\Rest\ObjectSerializer;

/**
 * InboundPlanSummary20240320 Class Doc Comment
 *
 * @category Class
 * @description A light-weight inbound plan.
 * @package  Webcom\Amazon\Rest\FulfillmentInboundApi20240320
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class InboundPlanSummary20240320 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;
    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'InboundPlanSummary';
    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'createdAt'      => '\DateTime',
        'inboundPlanId'  => 'string',
        'lastUpdatedAt'  => '\DateTime',
        'marketplaceIds' => 'string[]',
        'name'           => 'string',
        'sourceAddress'  => '\Webcom\Amazon\Rest\FulfillmentInboundApi20240320\Model\Address20240320',
        'status'         => 'string',
    ];
    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'createdAt'      => 'date-time',
        'inboundPlanId'  => null,
        'lastUpdatedAt'  => 'date-time',
        'marketplaceIds' => null,
        'name'           => null,
        'sourceAddress'  => null,
        'status'         => null,
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'createdAt'      => 'createdAt',
        'inboundPlanId'  => 'inboundPlanId',
        'lastUpdatedAt'  => 'lastUpdatedAt',
        'marketplaceIds' => 'marketplaceIds',
        'name'           => 'name',
        'sourceAddress'  => 'sourceAddress',
        'status'         => 'status',
    ];
    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'createdAt'      => 'setCreatedAt',
        'inboundPlanId'  => 'setInboundPlanId',
        'lastUpdatedAt'  => 'setLastUpdatedAt',
        'marketplaceIds' => 'setMarketplaceIds',
        'name'           => 'setName',
        'sourceAddress'  => 'setSourceAddress',
        'status'         => 'setStatus',
    ];
    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'createdAt'      => 'getCreatedAt',
        'inboundPlanId'  => 'getInboundPlanId',
        'lastUpdatedAt'  => 'getLastUpdatedAt',
        'marketplaceIds' => 'getMarketplaceIds',
        'name'           => 'getName',
        'sourceAddress'  => 'getSourceAddress',
        'status'         => 'getStatus',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['createdAt'] = $data['createdAt'] ?? null;
        $this->container['inboundPlanId'] = $data['inboundPlanId'] ?? null;
        $this->container['lastUpdatedAt'] = $data['lastUpdatedAt'] ?? null;
        $this->container['marketplaceIds'] = $data['marketplaceIds'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['sourceAddress'] = $data['sourceAddress'] ?? null;
        $this->container['status'] = $data['status'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        if ($this->container['inboundPlanId'] === null) {
            $invalidProperties[] = "'inboundPlanId' can't be null";
        }
        if ((mb_strlen($this->container['inboundPlanId']) > 38)) {
            $invalidProperties[] = "invalid value for 'inboundPlanId', the character length must be smaller than or equal to 38.";
        }

        if ((mb_strlen($this->container['inboundPlanId']) < 38)) {
            $invalidProperties[] = "invalid value for 'inboundPlanId', the character length must be bigger than or equal to 38.";
        }

        if (!preg_match("/^[a-zA-Z0-9-]*$/", $this->container['inboundPlanId'])) {
            $invalidProperties[] = "invalid value for 'inboundPlanId', must be conform to the pattern /^[a-zA-Z0-9-]*$/.";
        }

        if ($this->container['lastUpdatedAt'] === null) {
            $invalidProperties[] = "'lastUpdatedAt' can't be null";
        }
        if ($this->container['marketplaceIds'] === null) {
            $invalidProperties[] = "'marketplaceIds' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['sourceAddress'] === null) {
            $invalidProperties[] = "'sourceAddress' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ((mb_strlen($this->container['status']) > 1024)) {
            $invalidProperties[] = "invalid value for 'status', the character length must be smaller than or equal to 1024.";
        }

        if ((mb_strlen($this->container['status']) < 1)) {
            $invalidProperties[] = "invalid value for 'status', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param \DateTime $createdAt The time at which the inbound plan was created. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) datetime format with pattern `yyyy-MM-ddTHH:mm:ssZ`.
     *
     * @return self
     */
    public function setCreatedAt($createdAt)
    {
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets inboundPlanId
     *
     * @return string
     */
    public function getInboundPlanId()
    {
        return $this->container['inboundPlanId'];
    }

    /**
     * Sets inboundPlanId
     *
     * @param string $inboundPlanId Identifier of an inbound plan.
     *
     * @return self
     */
    public function setInboundPlanId($inboundPlanId)
    {
        if ((mb_strlen($inboundPlanId) > 38)) {
            throw new \InvalidArgumentException('invalid length for $inboundPlanId when calling InboundPlanSummary20240320., must be smaller than or equal to 38.');
        }
        if ((mb_strlen($inboundPlanId) < 38)) {
            throw new \InvalidArgumentException('invalid length for $inboundPlanId when calling InboundPlanSummary20240320., must be bigger than or equal to 38.');
        }
        if ((!preg_match("/^[a-zA-Z0-9-]*$/", $inboundPlanId))) {
            throw new \InvalidArgumentException("invalid value for $inboundPlanId when calling InboundPlanSummary20240320., must conform to the pattern /^[a-zA-Z0-9-]*$/.");
        }

        $this->container['inboundPlanId'] = $inboundPlanId;

        return $this;
    }

    /**
     * Gets lastUpdatedAt
     *
     * @return \DateTime
     */
    public function getLastUpdatedAt()
    {
        return $this->container['lastUpdatedAt'];
    }

    /**
     * Sets lastUpdatedAt
     *
     * @param \DateTime $lastUpdatedAt The time at which the inbound plan was last updated. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) datetime format with pattern `yyyy-MM-ddTHH:mm:ssZ`.
     *
     * @return self
     */
    public function setLastUpdatedAt($lastUpdatedAt)
    {
        $this->container['lastUpdatedAt'] = $lastUpdatedAt;

        return $this;
    }

    /**
     * Gets marketplaceIds
     *
     * @return string[]
     */
    public function getMarketplaceIds()
    {
        return $this->container['marketplaceIds'];
    }

    /**
     * Sets marketplaceIds
     *
     * @param string[] $marketplaceIds A list of marketplace IDs.
     *
     * @return self
     */
    public function setMarketplaceIds($marketplaceIds)
    {
        $this->container['marketplaceIds'] = $marketplaceIds;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Human-readable name of the inbound plan.
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets sourceAddress
     *
     * @return \Webcom\Amazon\Rest\FulfillmentInboundApi20240320\Model\Address20240320
     */
    public function getSourceAddress()
    {
        return $this->container['sourceAddress'];
    }

    /**
     * Sets sourceAddress
     *
     * @param \Webcom\Amazon\Rest\FulfillmentInboundApi20240320\Model\Address20240320 $sourceAddress sourceAddress
     *
     * @return self
     */
    public function setSourceAddress($sourceAddress)
    {
        $this->container['sourceAddress'] = $sourceAddress;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status The current status of the inbound plan. Possible values: `ACTIVE`, `VOIDED`, `SHIPPED`, `ERRORED`.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if ((mb_strlen($status) > 1024)) {
            throw new \InvalidArgumentException('invalid length for $status when calling InboundPlanSummary20240320., must be smaller than or equal to 1024.');
        }
        if ((mb_strlen($status) < 1)) {
            throw new \InvalidArgumentException('invalid length for $status when calling InboundPlanSummary20240320., must be bigger than or equal to 1.');
        }

        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed $value Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


