<?php
/**
 * DeliveryPreferencesV0
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Webcom\Amazon\Rest\OrdersApiV0
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Selling Partner API for Orders
 *
 * Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Webcom\Amazon\Rest\OrdersApiV0\Model;

use \Webcom\Amazon\Rest\ModelInterface;
use \ArrayAccess;
use \Webcom\Amazon\Rest\ObjectSerializer;

/**
 * DeliveryPreferencesV0 Class Doc Comment
 *
 * @category Class
 * @description Contains all of the delivery instructions provided by the customer for the shipping address.
 * @package  Webcom\Amazon\Rest\OrdersApiV0
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class DeliveryPreferencesV0 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DeliveryPreferences';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'dropOffLocation' => 'string',
        'preferredDeliveryTime' => '\Webcom\Amazon\Rest\OrdersApiV0\Model\PreferredDeliveryTimeV0',
        'otherAttributes' => '\Webcom\Amazon\Rest\OrdersApiV0\Model\OtherDeliveryAttributesV0[]',
        'addressInstructions' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'dropOffLocation' => null,
        'preferredDeliveryTime' => null,
        'otherAttributes' => null,
        'addressInstructions' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'dropOffLocation' => 'DropOffLocation',
        'preferredDeliveryTime' => 'PreferredDeliveryTime',
        'otherAttributes' => 'OtherAttributes',
        'addressInstructions' => 'AddressInstructions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'dropOffLocation' => 'setDropOffLocation',
        'preferredDeliveryTime' => 'setPreferredDeliveryTime',
        'otherAttributes' => 'setOtherAttributes',
        'addressInstructions' => 'setAddressInstructions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'dropOffLocation' => 'getDropOffLocation',
        'preferredDeliveryTime' => 'getPreferredDeliveryTime',
        'otherAttributes' => 'getOtherAttributes',
        'addressInstructions' => 'getAddressInstructions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['dropOffLocation'] = $data['dropOffLocation'] ?? null;
        $this->container['preferredDeliveryTime'] = $data['preferredDeliveryTime'] ?? null;
        $this->container['otherAttributes'] = $data['otherAttributes'] ?? null;
        $this->container['addressInstructions'] = $data['addressInstructions'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets dropOffLocation
     *
     * @return string|null
     */
    public function getDropOffLocation()
    {
        return $this->container['dropOffLocation'];
    }

    /**
     * Sets dropOffLocation
     *
     * @param string|null $dropOffLocation Drop-off location selected by the customer.
     *
     * @return self
     */
    public function setDropOffLocation($dropOffLocation)
    {
        $this->container['dropOffLocation'] = $dropOffLocation;

        return $this;
    }

    /**
     * Gets preferredDeliveryTime
     *
     * @return \Webcom\Amazon\Rest\OrdersApiV0\Model\PreferredDeliveryTimeV0|null
     */
    public function getPreferredDeliveryTime()
    {
        return $this->container['preferredDeliveryTime'];
    }

    /**
     * Sets preferredDeliveryTime
     *
     * @param \Webcom\Amazon\Rest\OrdersApiV0\Model\PreferredDeliveryTimeV0|null $preferredDeliveryTime preferredDeliveryTime
     *
     * @return self
     */
    public function setPreferredDeliveryTime($preferredDeliveryTime)
    {
        $this->container['preferredDeliveryTime'] = $preferredDeliveryTime;

        return $this;
    }

    /**
     * Gets otherAttributes
     *
     * @return \Webcom\Amazon\Rest\OrdersApiV0\Model\OtherDeliveryAttributesV0[]|null
     */
    public function getOtherAttributes()
    {
        return $this->container['otherAttributes'];
    }

    /**
     * Sets otherAttributes
     *
     * @param \Webcom\Amazon\Rest\OrdersApiV0\Model\OtherDeliveryAttributesV0[]|null $otherAttributes Enumerated list of miscellaneous delivery attributes associated with the shipping address.
     *
     * @return self
     */
    public function setOtherAttributes($otherAttributes)
    {
        $this->container['otherAttributes'] = $otherAttributes;

        return $this;
    }

    /**
     * Gets addressInstructions
     *
     * @return string|null
     */
    public function getAddressInstructions()
    {
        return $this->container['addressInstructions'];
    }

    /**
     * Sets addressInstructions
     *
     * @param string|null $addressInstructions Building instructions, nearby landmark or navigation instructions.
     *
     * @return self
     */
    public function setAddressInstructions($addressInstructions)
    {
        $this->container['addressInstructions'] = $addressInstructions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


