<?php
/**
 * OperationalConfiguration20200701
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Webcom\Amazon\Rest\SupplySourcesApi20200701
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Selling Partner API for Supply Sources
 *
 * Manage configurations and capabilities of seller supply sources.
 *
 * The version of the OpenAPI document: 2020-07-01
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Webcom\Amazon\Rest\SupplySourcesApi20200701\Model;

use \Webcom\Amazon\Rest\ModelInterface;
use \ArrayAccess;
use \Webcom\Amazon\Rest\ObjectSerializer;

/**
 * OperationalConfiguration20200701 Class Doc Comment
 *
 * @category Class
 * @description The operational configuration of &#x60;supplySources&#x60;.
 * @package  Webcom\Amazon\Rest\SupplySourcesApi20200701
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class OperationalConfiguration20200701 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OperationalConfiguration';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'contactDetails' => '\Webcom\Amazon\Rest\SupplySourcesApi20200701\Model\ContactDetails20200701',
        'throughputConfig' => '\Webcom\Amazon\Rest\SupplySourcesApi20200701\Model\ThroughputConfig20200701',
        'operatingHoursByDay' => '\Webcom\Amazon\Rest\SupplySourcesApi20200701\Model\OperatingHoursByDay20200701',
        'handlingTime' => '\Webcom\Amazon\Rest\SupplySourcesApi20200701\Model\Duration20200701'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'contactDetails' => null,
        'throughputConfig' => null,
        'operatingHoursByDay' => null,
        'handlingTime' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'contactDetails' => 'contactDetails',
        'throughputConfig' => 'throughputConfig',
        'operatingHoursByDay' => 'operatingHoursByDay',
        'handlingTime' => 'handlingTime'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'contactDetails' => 'setContactDetails',
        'throughputConfig' => 'setThroughputConfig',
        'operatingHoursByDay' => 'setOperatingHoursByDay',
        'handlingTime' => 'setHandlingTime'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'contactDetails' => 'getContactDetails',
        'throughputConfig' => 'getThroughputConfig',
        'operatingHoursByDay' => 'getOperatingHoursByDay',
        'handlingTime' => 'getHandlingTime'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['contactDetails'] = $data['contactDetails'] ?? null;
        $this->container['throughputConfig'] = $data['throughputConfig'] ?? null;
        $this->container['operatingHoursByDay'] = $data['operatingHoursByDay'] ?? null;
        $this->container['handlingTime'] = $data['handlingTime'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets contactDetails
     *
     * @return \Webcom\Amazon\Rest\SupplySourcesApi20200701\Model\ContactDetails20200701|null
     */
    public function getContactDetails()
    {
        return $this->container['contactDetails'];
    }

    /**
     * Sets contactDetails
     *
     * @param \Webcom\Amazon\Rest\SupplySourcesApi20200701\Model\ContactDetails20200701|null $contactDetails contactDetails
     *
     * @return self
     */
    public function setContactDetails($contactDetails)
    {
        $this->container['contactDetails'] = $contactDetails;

        return $this;
    }

    /**
     * Gets throughputConfig
     *
     * @return \Webcom\Amazon\Rest\SupplySourcesApi20200701\Model\ThroughputConfig20200701|null
     */
    public function getThroughputConfig()
    {
        return $this->container['throughputConfig'];
    }

    /**
     * Sets throughputConfig
     *
     * @param \Webcom\Amazon\Rest\SupplySourcesApi20200701\Model\ThroughputConfig20200701|null $throughputConfig throughputConfig
     *
     * @return self
     */
    public function setThroughputConfig($throughputConfig)
    {
        $this->container['throughputConfig'] = $throughputConfig;

        return $this;
    }

    /**
     * Gets operatingHoursByDay
     *
     * @return \Webcom\Amazon\Rest\SupplySourcesApi20200701\Model\OperatingHoursByDay20200701|null
     */
    public function getOperatingHoursByDay()
    {
        return $this->container['operatingHoursByDay'];
    }

    /**
     * Sets operatingHoursByDay
     *
     * @param \Webcom\Amazon\Rest\SupplySourcesApi20200701\Model\OperatingHoursByDay20200701|null $operatingHoursByDay operatingHoursByDay
     *
     * @return self
     */
    public function setOperatingHoursByDay($operatingHoursByDay)
    {
        $this->container['operatingHoursByDay'] = $operatingHoursByDay;

        return $this;
    }

    /**
     * Gets handlingTime
     *
     * @return \Webcom\Amazon\Rest\SupplySourcesApi20200701\Model\Duration20200701|null
     */
    public function getHandlingTime()
    {
        return $this->container['handlingTime'];
    }

    /**
     * Sets handlingTime
     *
     * @param \Webcom\Amazon\Rest\SupplySourcesApi20200701\Model\Duration20200701|null $handlingTime handlingTime
     *
     * @return self
     */
    public function setHandlingTime($handlingTime)
    {
        $this->container['handlingTime'] = $handlingTime;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


