<?php
/**
 * ProgramType
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Webcom\Amazon\Rest\DeliveryByAmazon
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Selling Partner API for Delivery Shipment Invoicing
 *
 * The Selling Partner API for Delivery Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s orders.
 *
 * The version of the OpenAPI document: 2022-07-01
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Webcom\Amazon\Rest\DeliveryByAmazon\Model;
use \Webcom\Amazon\Rest\ObjectSerializer;

/**
 * ProgramType Class Doc Comment
 *
 * @category Class
 * @description The Amazon program type.
 * @package  Webcom\Amazon\Rest\DeliveryByAmazon
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProgramType
{
    /**
     * Possible values of this enum
     */
    const EASY_SHIP = 'EasyShip';
    const FBA_ON_SITE = 'FbaOnSite';
    const SELF_SHIP = 'SelfShip';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EASY_SHIP,
            self::FBA_ON_SITE,
            self::SELF_SHIP,
        ];
    }
}


