<?php
/**
 * Order20260101
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Webcom\Amazon\Rest\OrdersApi20260101
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for Orders
 *
 * The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Webcom\Amazon\Rest\OrdersApi20260101\Model;

use \Webcom\Amazon\Rest\ModelInterface;
use \ArrayAccess;
use \Webcom\Amazon\Rest\ObjectSerializer;

/**
 * Order20260101 Class Doc Comment
 *
 * @category Class
 * @description Comprehensive information about a customer order.
 * @package  Webcom\Amazon\Rest\OrdersApi20260101
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class Order20260101 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Order';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'orderId' => 'string',
        'orderAliases' => '\Webcom\Amazon\Rest\OrdersApi20260101\Model\Alias20260101[]',
        'createdTime' => '\DateTime',
        'lastUpdatedTime' => '\DateTime',
        'programs' => 'string[]',
        'associatedOrders' => '\Webcom\Amazon\Rest\OrdersApi20260101\Model\AssociatedOrder20260101[]',
        'salesChannel' => '\Webcom\Amazon\Rest\OrdersApi20260101\Model\SalesChannel20260101',
        'buyer' => '\Webcom\Amazon\Rest\OrdersApi20260101\Model\Buyer20260101',
        'recipient' => '\Webcom\Amazon\Rest\OrdersApi20260101\Model\Recipient20260101',
        'proceeds' => '\Webcom\Amazon\Rest\OrdersApi20260101\Model\OrderProceeds20260101',
        'fulfillment' => '\Webcom\Amazon\Rest\OrdersApi20260101\Model\OrderFulfillment20260101',
        'orderItems' => '\Webcom\Amazon\Rest\OrdersApi20260101\Model\OrderItem20260101[]',
        'packages' => '\Webcom\Amazon\Rest\OrdersApi20260101\Model\OrderPackage20260101[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'orderId' => null,
        'orderAliases' => null,
        'createdTime' => 'date-time',
        'lastUpdatedTime' => 'date-time',
        'programs' => null,
        'associatedOrders' => null,
        'salesChannel' => null,
        'buyer' => null,
        'recipient' => null,
        'proceeds' => null,
        'fulfillment' => null,
        'orderItems' => null,
        'packages' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'orderId' => 'orderId',
        'orderAliases' => 'orderAliases',
        'createdTime' => 'createdTime',
        'lastUpdatedTime' => 'lastUpdatedTime',
        'programs' => 'programs',
        'associatedOrders' => 'associatedOrders',
        'salesChannel' => 'salesChannel',
        'buyer' => 'buyer',
        'recipient' => 'recipient',
        'proceeds' => 'proceeds',
        'fulfillment' => 'fulfillment',
        'orderItems' => 'orderItems',
        'packages' => 'packages'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'orderId' => 'setOrderId',
        'orderAliases' => 'setOrderAliases',
        'createdTime' => 'setCreatedTime',
        'lastUpdatedTime' => 'setLastUpdatedTime',
        'programs' => 'setPrograms',
        'associatedOrders' => 'setAssociatedOrders',
        'salesChannel' => 'setSalesChannel',
        'buyer' => 'setBuyer',
        'recipient' => 'setRecipient',
        'proceeds' => 'setProceeds',
        'fulfillment' => 'setFulfillment',
        'orderItems' => 'setOrderItems',
        'packages' => 'setPackages'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'orderId' => 'getOrderId',
        'orderAliases' => 'getOrderAliases',
        'createdTime' => 'getCreatedTime',
        'lastUpdatedTime' => 'getLastUpdatedTime',
        'programs' => 'getPrograms',
        'associatedOrders' => 'getAssociatedOrders',
        'salesChannel' => 'getSalesChannel',
        'buyer' => 'getBuyer',
        'recipient' => 'getRecipient',
        'proceeds' => 'getProceeds',
        'fulfillment' => 'getFulfillment',
        'orderItems' => 'getOrderItems',
        'packages' => 'getPackages'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['orderId'] = $data['orderId'] ?? null;
        $this->container['orderAliases'] = $data['orderAliases'] ?? null;
        $this->container['createdTime'] = $data['createdTime'] ?? null;
        $this->container['lastUpdatedTime'] = $data['lastUpdatedTime'] ?? null;
        $this->container['programs'] = $data['programs'] ?? null;
        $this->container['associatedOrders'] = $data['associatedOrders'] ?? null;
        $this->container['salesChannel'] = $data['salesChannel'] ?? null;
        $this->container['buyer'] = $data['buyer'] ?? null;
        $this->container['recipient'] = $data['recipient'] ?? null;
        $this->container['proceeds'] = $data['proceeds'] ?? null;
        $this->container['fulfillment'] = $data['fulfillment'] ?? null;
        $this->container['orderItems'] = $data['orderItems'] ?? null;
        $this->container['packages'] = $data['packages'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['orderId'] === null) {
            $invalidProperties[] = "'orderId' can't be null";
        }
        if ($this->container['createdTime'] === null) {
            $invalidProperties[] = "'createdTime' can't be null";
        }
        if ($this->container['lastUpdatedTime'] === null) {
            $invalidProperties[] = "'lastUpdatedTime' can't be null";
        }
        if ($this->container['salesChannel'] === null) {
            $invalidProperties[] = "'salesChannel' can't be null";
        }
        if ($this->container['orderItems'] === null) {
            $invalidProperties[] = "'orderItems' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets orderId
     *
     * @return string
     */
    public function getOrderId()
    {
        return $this->container['orderId'];
    }

    /**
     * Sets orderId
     *
     * @param string $orderId An Amazon-defined order identifier.
     *
     * @return self
     */
    public function setOrderId($orderId)
    {
        $this->container['orderId'] = $orderId;

        return $this;
    }

    /**
     * Gets orderAliases
     *
     * @return \Webcom\Amazon\Rest\OrdersApi20260101\Model\Alias20260101[]|null
     */
    public function getOrderAliases()
    {
        return $this->container['orderAliases'];
    }

    /**
     * Sets orderAliases
     *
     * @param \Webcom\Amazon\Rest\OrdersApi20260101\Model\Alias20260101[]|null $orderAliases Alternative identifiers that can be used to reference this order, such as seller-defined order numbers.
     *
     * @return self
     */
    public function setOrderAliases($orderAliases)
    {
        $this->container['orderAliases'] = $orderAliases;

        return $this;
    }

    /**
     * Gets createdTime
     *
     * @return \DateTime
     */
    public function getCreatedTime()
    {
        return $this->container['createdTime'];
    }

    /**
     * Sets createdTime
     *
     * @param \DateTime $createdTime The time when the customer placed the order. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     *
     * @return self
     */
    public function setCreatedTime($createdTime)
    {
        $this->container['createdTime'] = $createdTime;

        return $this;
    }

    /**
     * Gets lastUpdatedTime
     *
     * @return \DateTime
     */
    public function getLastUpdatedTime()
    {
        return $this->container['lastUpdatedTime'];
    }

    /**
     * Sets lastUpdatedTime
     *
     * @param \DateTime $lastUpdatedTime The most recent time when any aspect of this order was modified by Amazon or the seller. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     *
     * @return self
     */
    public function setLastUpdatedTime($lastUpdatedTime)
    {
        $this->container['lastUpdatedTime'] = $lastUpdatedTime;

        return $this;
    }

    /**
     * Gets programs
     *
     * @return string[]|null
     */
    public function getPrograms()
    {
        return $this->container['programs'];
    }

    /**
     * Sets programs
     *
     * @param string[]|null $programs Special programs associated with this order that may affect fulfillment or customer experience.   **Possible values**: `AMAZON_BAZAAR`, `AMAZON_BUSINESS`,  `AMAZON_EASY_SHIP`, `AMAZON_HAUL`, `DELIVERY_BY_AMAZON`, `FBM_SHIP_PLUS`, `IN_STORE_PICK_UP`, `PREMIUM`, `PREORDER`, `PRIME`
     *
     * @return self
     */
    public function setPrograms($programs)
    {
        $this->container['programs'] = $programs;

        return $this;
    }

    /**
     * Gets associatedOrders
     *
     * @return \Webcom\Amazon\Rest\OrdersApi20260101\Model\AssociatedOrder20260101[]|null
     */
    public function getAssociatedOrders()
    {
        return $this->container['associatedOrders'];
    }

    /**
     * Sets associatedOrders
     *
     * @param \Webcom\Amazon\Rest\OrdersApi20260101\Model\AssociatedOrder20260101[]|null $associatedOrders Other orders that have a direct relationship to this order, such as replacement or exchange orders.
     *
     * @return self
     */
    public function setAssociatedOrders($associatedOrders)
    {
        $this->container['associatedOrders'] = $associatedOrders;

        return $this;
    }

    /**
     * Gets salesChannel
     *
     * @return \Webcom\Amazon\Rest\OrdersApi20260101\Model\SalesChannel20260101
     */
    public function getSalesChannel()
    {
        return $this->container['salesChannel'];
    }

    /**
     * Sets salesChannel
     *
     * @param \Webcom\Amazon\Rest\OrdersApi20260101\Model\SalesChannel20260101 $salesChannel salesChannel
     *
     * @return self
     */
    public function setSalesChannel($salesChannel)
    {
        $this->container['salesChannel'] = $salesChannel;

        return $this;
    }

    /**
     * Gets buyer
     *
     * @return \Webcom\Amazon\Rest\OrdersApi20260101\Model\Buyer20260101|null
     */
    public function getBuyer()
    {
        return $this->container['buyer'];
    }

    /**
     * Sets buyer
     *
     * @param \Webcom\Amazon\Rest\OrdersApi20260101\Model\Buyer20260101|null $buyer buyer
     *
     * @return self
     */
    public function setBuyer($buyer)
    {
        $this->container['buyer'] = $buyer;

        return $this;
    }

    /**
     * Gets recipient
     *
     * @return \Webcom\Amazon\Rest\OrdersApi20260101\Model\Recipient20260101|null
     */
    public function getRecipient()
    {
        return $this->container['recipient'];
    }

    /**
     * Sets recipient
     *
     * @param \Webcom\Amazon\Rest\OrdersApi20260101\Model\Recipient20260101|null $recipient recipient
     *
     * @return self
     */
    public function setRecipient($recipient)
    {
        $this->container['recipient'] = $recipient;

        return $this;
    }

    /**
     * Gets proceeds
     *
     * @return \Webcom\Amazon\Rest\OrdersApi20260101\Model\OrderProceeds20260101|null
     */
    public function getProceeds()
    {
        return $this->container['proceeds'];
    }

    /**
     * Sets proceeds
     *
     * @param \Webcom\Amazon\Rest\OrdersApi20260101\Model\OrderProceeds20260101|null $proceeds proceeds
     *
     * @return self
     */
    public function setProceeds($proceeds)
    {
        $this->container['proceeds'] = $proceeds;

        return $this;
    }

    /**
     * Gets fulfillment
     *
     * @return \Webcom\Amazon\Rest\OrdersApi20260101\Model\OrderFulfillment20260101|null
     */
    public function getFulfillment()
    {
        return $this->container['fulfillment'];
    }

    /**
     * Sets fulfillment
     *
     * @param \Webcom\Amazon\Rest\OrdersApi20260101\Model\OrderFulfillment20260101|null $fulfillment fulfillment
     *
     * @return self
     */
    public function setFulfillment($fulfillment)
    {
        $this->container['fulfillment'] = $fulfillment;

        return $this;
    }

    /**
     * Gets orderItems
     *
     * @return \Webcom\Amazon\Rest\OrdersApi20260101\Model\OrderItem20260101[]
     */
    public function getOrderItems()
    {
        return $this->container['orderItems'];
    }

    /**
     * Sets orderItems
     *
     * @param \Webcom\Amazon\Rest\OrdersApi20260101\Model\OrderItem20260101[] $orderItems The list of all order items included in this order.
     *
     * @return self
     */
    public function setOrderItems($orderItems)
    {
        $this->container['orderItems'] = $orderItems;

        return $this;
    }

    /**
     * Gets packages
     *
     * @return \Webcom\Amazon\Rest\OrdersApi20260101\Model\OrderPackage20260101[]|null
     */
    public function getPackages()
    {
        return $this->container['packages'];
    }

    /**
     * Sets packages
     *
     * @param \Webcom\Amazon\Rest\OrdersApi20260101\Model\OrderPackage20260101[]|null $packages Shipping packages created for this order, including tracking information. **Note:** Only available for merchant-fulfilled (FBM) orders.
     *
     * @return self
     */
    public function setPackages($packages)
    {
        $this->container['packages'] = $packages;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


